title: m-fr.cz
author: Michal Franc
description: m-fr.cz. Site of Michal Franc.

github_username: m-fr
rss: blog

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

include: [".well-known"]

images: "/assets/images/"
thumbnails: "/assets/thumbnails/"

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - blog.markdown
  - gallery.markdown
  - about.markdown

collections:
  gallery:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

feed:
  collections:
    gallery:
      path: "gallery.xml"

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
