title: m-fr.cz
author:
  name: Michal Franc
description: m-fr.cz. Site of Michal Franc.

include: [".well-known"]

images: "/assets/images/"
thumbnails: "/assets/thumbnails/"

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  skin: auto
  social_links:
    github: m-fr
    flickr: 195985989@N02

header_pages:
  - blog.markdown
  - gallery.markdown
  - about.markdown

collections:
  gallery:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

feed:
  collections:
    - gallery
    - posts

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
